package com.hnit.learning_shop.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class UserNotes {
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notes.id
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notes.uid
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notes.content
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notes.agreeCnt
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    private Integer agreecnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notes.readTime
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    private Date readtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notes.createTime
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notes.id
     *
     * @return the value of user_notes.id
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notes.id
     *
     * @param id the value for user_notes.id
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notes.uid
     *
     * @return the value of user_notes.uid
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notes.uid
     *
     * @param uid the value for user_notes.uid
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notes.content
     *
     * @return the value of user_notes.content
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notes.content
     *
     * @param content the value for user_notes.content
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notes.agreeCnt
     *
     * @return the value of user_notes.agreeCnt
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public Integer getAgreecnt() {
        return agreecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notes.agreeCnt
     *
     * @param agreecnt the value for user_notes.agreeCnt
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public void setAgreecnt(Integer agreecnt) {
        this.agreecnt = agreecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notes.readTime
     *
     * @return the value of user_notes.readTime
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public Date getReadtime() {
        return readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notes.readTime
     *
     * @param readtime the value for user_notes.readTime
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public void setReadtime(Date readtime) {
        this.readtime = readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notes.createTime
     *
     * @return the value of user_notes.createTime
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notes.createTime
     *
     * @param createtime the value for user_notes.createTime
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}