spring:
    mvc:
      view:
         prefix: WEB-INF/jsp/
         suffix: .jsp
         
    datasource:
      url: jdbc:mysql://localhost:3306/scott
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver
      
#  日志输出
logging:
  level:
    com:
      example: trace
    
