#DB Configuration:
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learning_shop?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: a
  http:
    multipart:
          enabled: true # 默认支持文件上传

  #Redis
  redis:
    host: www.hujiatai.cn
    port: 6379
  #mvc
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
      
# mail发送
  mail:
    host:smtp.qq.com
    username:879798231@qq.com
    password:rdxungqedajpbeba
    default-encoding:UTF-8

logging:
  level:
    com:
      hnit: debug
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# web端登录界面
my:
  security:
    browser:
      loginPage: /login.jsp
# 登录成功后的处理方式（跳转，返回json）
#my.security.browser.loginType = REDIRECT


