#DB Configuration:
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learning_shop?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: abc

  #Redis
  redis:
    host: www.hujiatai.cn
    port: 6379
  #mvc
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
      
      #邮件服务配置
  mail:
   #邮箱服务器地址
   host: smtp.qq.com
   #用户
   username: 1447076355@qq.com
   #发送密码  注意该密码不是邮箱密码，是邮箱开通权限后的授权密码
   password: aaa
   #默认字符集编码
   default-encoding: UTF-8
#发送地址
mail:
 fromMail:
      addr: 1447076355@qq.com

logging:
  level:
    com:
      jt: error
server:
  port: 80

# web端登录界面
my:
  security:
    browser:
      loginPage: /login.jsp
      

# 登录成功后的处理方式（跳转，返回json）
#my.security.browser.loginType = REDIRECT
