#DB Configuration:
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learning_shop
    username: root
    password: a

  #Redis
  redis:
    host: www.hujiatai.cn
    port: 6379
  #mvc
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
      
  mail:
    host: smtp.qq.com
    username: 1447076355@qq.com # 这里填写个人的qq邮箱
    password: aghmefjkwysdihfg # 注：这里不是qq邮箱的密码，而是授权码
    default-encoding: UTF-8
#发送地址
mail:
 fromMail:
      addr: 1447076355@qq.com

logging:
  level:
    com:
      hnit: debug
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# web端登录界面
my:
  security:
    browser:
      loginPage: /login.jsp
      

# 登录成功后的处理方式（跳转，返回json）
#my.security.browser.loginType = REDIRECT
