package com.hnit.learning_shop.dao;

import com.hnit.learning_shop.entity.UserNotes;
import com.hnit.learning_shop.entity.UserNotesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserNotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    long countByExample(UserNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int deleteByExample(UserNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int insert(UserNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int insertSelective(UserNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    List<UserNotes> selectByExample(UserNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    UserNotes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserNotes record, @Param("example") UserNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int updateByExample(@Param("record") UserNotes record, @Param("example") UserNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int updateByPrimaryKeySelective(UserNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_notes
     *
     * @mbg.generated Tue Aug 27 10:03:51 CST 2019
     */
    int updateByPrimaryKey(UserNotes record);
}